server:
  port: 8001

spring:
  application:
    name: FINPLAY-MAIN-APP

  datasource:
    url: jdbc:mysql://localhost:3306/finplay
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
aws:
  cognito:
    clientId: 1g1geruvci4pl6n46tp1r08aeb
    clientSecret: org6ump00mobfnf1kbjb17uvpovnvoa5gqf309u1u2n1g1ktvus
    userPoolId: us-east-1_qIoijIZjb
    region: us-east-1
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always