server:
  port: 8001

spring:
  application:
    name: FINPLAY-MAIN-APP

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
aws:
  iam:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  cognito:
    clientId: ${COGNITO_CLIENT_ID}
    clientSecret: ${COGNITO_CLIENT_SECRET}
    userPoolId: ${COGNITO_USER_POOL_ID}
    region: ${AWS_REGION}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always