server:
  port: 8001

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 59015pa352u79b32csg7p29f
            client-secret: 1r8ceb6k642da164sbhkanunm1f633o95h32gakqnpt89nkh7psd
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8001/login/oauth2/code/cognito
            client-name: Cognito
        provider:
          cognito:
            authorization-uri: https://finplayapp.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://finplayapp.auth.us-east-1.amazoncognito.com/oauth2/token
            user-info-uri: https://finplayapp.auth.us-east-1.amazoncognito.com/oauth2/userInfo

  application:
    name: FINPLAY-MAIN-APP

  datasource:
    url: jdbc:mysql://localhost:3306/finplay
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

cognito:
  userPoolId: us-east-1_oWCG4e8UI
  clientId: 59015pa352u79b32csg7p29f
  clientSecret: 1r8ceb6k642da164sbhkanunm1f633o95h32gakqnpt89nkh7psd
  region: us-east-1
  resourceServer:
    id: finplay-resource-server
    jwtIssuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_oWCG4e8UI